version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/ctemps-app
hooks:
  AfterInstall:
    - location: codedeploy/install_dependencies.sh
      timeout: 900
      runas: root
  ApplicationStart:
    - location: codedeploy/start_app.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: codedeploy/stop_app.sh
      timeout: 300
      runas: root
